version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db

  etl:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASS: ${MONGO_INITDB_ROOT_PASSWORD}
      USUARIO: ${USUARIO}
      CONTRASENA: ${CONTRASENA}
      PUBLICACIONES_BUSCADAS: ${PUBLICACIONES_BUSCADAS}
    volumes:
      - .:/app
    command: ["./run_scripts.sh"]

volumes:
  mongo_data:
